linters:
  disable:
    - depguard
    - exhaustruct
    - funlen
    - gochecknoglobals
    - nestif
    - nlreturn
    - perfsprint
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
issues:
  exclude-files:
    - constant/regexes.go
